"use client";

import { useMemo } from "react";
import type { HmiScreenDefinition } from "@/lib/hmiSchema";
import type { HmiStreamPayload } from "@/lib/server/hmiEngine";
import { useHmiCopilot } from "@/context/HmiCopilotContext";
import { HmiRenderer } from "./HmiRenderer";

const STATE_LABEL: Record<string, string> = { STARTING: "Starting…", RUNNING: "Running", STOPPED: "Stopped", SAFE_MODE: "Safe Mode" };
const STATE_TONE: Record<string, "ok" | "warn" | "critical" | "idle"> = { STARTING: "ok", RUNNING: "ok", STOPPED: "idle", SAFE_MODE: "critical" };

/**
 * Keep the control buttons and status header on ANY runtime screen (engine- or
 * copilot-generated) synchronised with the live machine state — so STOP/START
 * availability always reflects the simulator, never a frozen snapshot.
 */
function withLiveState(screen: HmiScreenDefinition, payload: HmiStreamPayload): HmiScreenDefinition {
  const ctx = payload.machineContext;
  const ms = ctx.runtime.machineState;
  const alarm = ctx.alarms.some((a) => a.state === "active");
  const enabledOf = (id: string) => ctx.operatorActions.find((a) => a.id === id)?.enabled ?? false;
  return {
    ...screen,
    widgets: screen.widgets.map((w) => {
      if (w.kind === "controlPair") {
        return {
          ...w,
          primary: { ...w.primary, enabled: enabledOf(w.primary.actionId) },
          secondary: { ...w.secondary, enabled: enabledOf(w.secondary.actionId) },
        };
      }
      if (w.kind === "statusHeader" && w.id === "status" && w.label === payload.context.deviceKind) {
        return { ...w, state: STATE_LABEL[ms] ?? "Running", tone: ms === "RUNNING" && alarm ? "warn" : STATE_TONE[ms] ?? "ok" };
      }
      return w;
    }),
  };
}

export function DynamicHmiPanel() {
  const {
    payload,
    screen,
    screenSource,
    highlight,
    goldenPath,
    goldenStep,
    goldenNext,
    goldenPrev,
    goldenExit,
    replay,
    replayT,
    replayFrame,
    replayPlaying,
    scrub,
    exitTimeTravel,
    replayPlayPause,
    replayStepEvent,
    runControl,
  } = useHmiCopilot();

  const step = goldenPath?.steps[goldenStep] ?? null;
  const driverPvId = payload?.primaryPvId;
  const driverVal = replayFrame && driverPvId ? replayFrame.values[driverPvId] : undefined;

  // Replay screens are historical reconstructions — leave them as recorded.
  // Every other screen gets its controls/status refreshed from live machine state.
  const shownScreen = useMemo(() => {
    if (!screen) return null;
    if (screenSource === "replay" || !payload) return screen;
    return withLiveState(screen, payload);
  }, [screen, screenSource, payload]);

  const onWidgetAction = (actionId: string) => {
    if (actionId === "STOP") void runControl("device_stop");
    else if (actionId === "START") void runControl("device_start");
    else if (actionId === "ACK") void runControl("acknowledge");
    else if (actionId === "RESOLVE") void runControl("resolve");
    else if (/OUTLET|INLET/.test(actionId)) void runControl("valve", { valveId: actionId as "OPEN_OUTLET" });
  };

  return (
    <section className="flex flex-col gap-3 p-3.5">
      <div className="flex items-center justify-between">
        <h2 className="text-[11px] font-semibold uppercase tracking-[0.14em] text-ink">Dynamic HMI</h2>
        <span className="text-[9.5px] font-semibold uppercase tracking-[0.12em] text-ink-faint">
          {screenSource === "replay" ? "Replay reconstruction" : screenSource === "copilot" ? "Generated by copilot" : "Generated at runtime"}
        </span>
      </div>

      {/* Golden Path guidance bar */}
      {goldenPath && step && (
        <div className="rounded-[6px] border border-accent-line bg-accent-wash px-3 py-2.5">
          <div className="flex items-center justify-between">
            <span className="text-[9.5px] font-bold uppercase tracking-[0.13em] text-accent-deep">
              Golden Path · Step {goldenStep + 1} of {goldenPath.steps.length}
            </span>
            <button onClick={goldenExit} className="text-[9px] font-semibold uppercase tracking-wide text-ink-faint hover:text-ink">
              Exit
            </button>
          </div>
          <div className="mt-1 text-[12.5px] font-semibold text-[#1f4b46]">{step.title}</div>
          <p className="mt-0.5 text-[11px] leading-snug text-[#2f5a55]">{step.instruction}</p>
          <div className="mt-2 flex items-center gap-2">
            <button onClick={goldenPrev} disabled={goldenStep === 0} className="rounded-[4px] border border-hairline bg-surface px-2.5 py-1.5 text-[9.5px] font-semibold uppercase tracking-wide text-ink-soft disabled:opacity-40">
              Prev
            </button>
            <button onClick={goldenNext} disabled={goldenStep >= goldenPath.steps.length - 1} className="rounded-[4px] border border-ink bg-ink px-3 py-1.5 text-[9.5px] font-semibold uppercase tracking-wide text-white disabled:opacity-40">
              Next Step
            </button>
            <span className="ml-auto text-[8.5px] text-ink-faint">{goldenPath.source}</span>
          </div>
        </div>
      )}

      {/* Time Travel replay bar */}
      {replay && replayT != null && (
        <div className="rounded-[6px] border border-ink px-3 py-2.5">
          <div className="flex items-center justify-between">
            <span className="text-[9.5px] font-bold uppercase tracking-[0.13em] text-ink">Time Travel Replay</span>
            <button onClick={exitTimeTravel} className="text-[9px] font-semibold uppercase tracking-wide text-accent-deep">
              Return to live
            </button>
          </div>
          <div className="mt-1.5 flex items-center gap-1.5">
            <button onClick={() => replayStepEvent(-1)} aria-label="Previous event" className="grid h-6 w-6 place-items-center rounded-[3px] border border-hairline bg-surface text-[10px] text-ink-soft hover:bg-surface-muted">
              ⏮
            </button>
            <button onClick={replayPlayPause} aria-label={replayPlaying ? "Pause" : "Play"} className="grid h-6 w-7 place-items-center rounded-[3px] border border-ink bg-ink text-[10px] text-white">
              {replayPlaying ? "❚❚" : "▶"}
            </button>
            <button onClick={() => replayStepEvent(1)} aria-label="Next event" className="grid h-6 w-6 place-items-center rounded-[3px] border border-hairline bg-surface text-[10px] text-ink-soft hover:bg-surface-muted">
              ⏭
            </button>
            <span className="ml-2 font-mono text-[11px] font-semibold text-ink">{replayFrame?.clock ?? ""}</span>
            {driverVal != null && (
              <span className={`ml-auto font-mono text-[10.5px] ${replayFrame?.alarm ? "text-warn" : "text-ink"}`}>
                {driverVal} · {replayFrame?.alarm ? `${replayFrame.alarm.label}` : "Normal"}
              </span>
            )}
          </div>
          <input
            type="range"
            min={replay.from}
            max={replay.to}
            step={1000}
            value={replayT}
            onChange={(e) => void scrub(Number(e.target.value))}
            className="mt-1.5 w-full accent-[color:var(--accent)]"
            aria-label="Replay timeline"
          />
          <ul className="mt-2 flex max-h-24 flex-col gap-1 overflow-y-auto border-t border-hairline-soft pt-1.5">
            {replay.events.map((e) => (
              <li key={e.id}>
                <button
                  onClick={() => void scrub(e.t)}
                  className={`flex w-full items-baseline gap-2 rounded-[3px] px-1 py-0.5 text-left text-[10px] hover:bg-surface-muted ${replayFrame && Math.abs(e.t - replayFrame.t) < 1500 ? "bg-surface-muted" : ""}`}
                >
                  <span className="font-mono text-ink-faint">{e.clock}</span>
                  <span className="text-ink-soft">{e.title}</span>
                </button>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* the generated screen */}
      {shownScreen ? (
        <div className="rounded-[6px] border border-ink">
          <div className="flex items-center justify-between border-b border-hairline bg-surface-muted px-3 py-2 text-[11.5px] font-semibold">
            <span>{shownScreen.screenTitle}</span>
            <span className="rounded-[3px] border border-accent-line bg-accent-wash px-1.5 py-px text-[8px] font-bold uppercase tracking-[0.1em] text-accent-deep">
              {screenSource === "replay" ? "Reconstructed" : "Auto-generated"}
            </span>
          </div>
          <div className="p-3">
            <HmiRenderer
              screen={shownScreen}
              highlight={highlight}
              stepLabel={goldenPath ? `Step ${goldenStep + 1}` : null}
              readOnly={screenSource === "replay"}
              onAction={onWidgetAction}
            />
          </div>
          <div className="flex items-center gap-2 border-t border-hairline px-3 py-2 text-[9px] font-semibold uppercase tracking-[0.11em] text-ink-faint">
            <span className="h-1.5 w-1.5 rounded-full bg-accent" />
            {shownScreen.footnote}
          </div>
        </div>
      ) : (
        <div className="rounded-[6px] border border-hairline px-3 py-6 text-center text-[11px] text-ink-faint">Waiting for machine context…</div>
      )}

      {shownScreen && <p className="text-[9.5px] leading-snug text-ink-faint">{shownScreen.rationale}</p>}
    </section>
  );
}
